### ISSUE TITLE
ui and ux issues (to-do)

### ISSUE THREAD

**Issue by jyotirmaygithub** [jyotirmaygithub/ComfortQuest#8]
- [x] search functionality is not working.
- [x] search icon is not visible -- of search component
- [x] scroll down component icon of the up arrow is not visible
- [x] show all photo and close all of the hotel details is not visible i think it should be in white color with the text as white also 
- [x] booking success page and registration success page--- home icons should be in the green color
- [ ] cancel booking route to for the cancellation of the hotel is not working
- [x] register hotel page -- should not any down scroll which is there.
- [x] backend  of the contact us need to write
- [x] login and sign up btns should be in blue 
- [x] footer 
- [x] issue in showing booked hotel same to every user
- [x] bug in the login and sign simple authentication 
- [x] refressing of the booked hotels is not working 
- [x] bug in the working of the nodemailer
- [x] search should visible where searching is possible 
- [x] ui of the search and its functioning 
- [ ] contact page btn turing grey on submit 
- [x] at booking first big circle and then booking success
- [ ] warning in imagePreview of img tag fix it
